#!/bin/sh

set -eu
umask 022

ARCH=${ARCH:-$(uname -m)}
GMAKE=${GMAKE:-gmake}
GZ=${GZ:-gz}

"$GZ" -cd flex.tar.gz | tar -x

cd    flex*/
mkdir build
cd    build

MAKE=$GMAKE \
../configure --prefix=/ \
             --host="$ARCH-linux-musl" \
             ac_cv_func_malloc_0_nonnull=yes \
             ac_cv_func_realloc_0_nonnull=yes

"$GMAKE"
"$GMAKE" DESTDIR="$PREFIX" install
