#!/bin/sh

set -eu
umask 022

ARCH=${ARCH:-$(uname -m)}
GMAKE=${GMAKE:-gmake}
GZ=${GZ:-gz}

"$GZ" -cd byacc.tar.gz | tar -x

cd    byacc*/
mkdir build
cd    build

MAKE=$GMAKE \
../configure --prefix=/ \
             --host="$ARCH-linux-musl" \
             --disable-btyacc

"$GMAKE"
"$GMAKE" DESTDIR="$PREFIX" install
