#!/bin/sh

set -eu
umask 022

ARCH=${ARCH:-$(uname -m)}
GMAKE=${GMAKE:-gmake}
GZ=${GZ:-gz}

"$GZ" -cd zlib.tar.gz | tar -x

cd    zlib*/
mkdir build
cd    build

MAKE=$GMAKE \
CC=${CC:-"$ARCH-linux-musl-cc"} \
../configure --prefix=/ \
             --const \
             --static

"$GMAKE"
"$GMAKE" DESTDIR="$PREFIX" install
